import {it,expect} from 'vitest';
import {GameKernel,ms} from '../../packages/game-core/src/index.js';
import {loadScenario,MemoryRunStore,validatedData} from '../../packages/kernel-adapters/src/index.js';
async function setup(){const data=loadScenario('scenarios/synthetic/kernel-smoke');data.pack.actions=[];const k=await GameKernel.create({runId:'r',ownerActorId:'p'},validatedData(data.pack),new MemoryRunStore());await k.execute({type:'CreateAccount',runId:'r',commandId:'create',actorId:'p',accountId:'a',initialCashFen:'10000000'});return k;}
const order=(id:string,side:'BUY'|'SELL',quantity='100')=>({runId:'r',commandId:id,actorId:'p',accountId:'a',type:'SubmitOrder' as const,securityId:'TEST_A',side,quantity,protectionPriceUnits:side==='BUY'?'120000':'100000'});
it('C01 B04 T+1 and exact independent 100088.90 baseline',async()=>{const k=await setup();await k.execute(order('buy','BUY'));await k.advanceTo('2020-01-02T09:35:00+08:00');expect(k.exportSnapshot('p').accounts.a!.availableCashFen).toBe(9899500n);expect((await k.execute(order('early','SELL'))).code).toBe('INSUFFICIENT_SELLABLE_QUANTITY');await k.advanceTo('2020-01-06T09:30:00+08:00');await k.execute(order('sell','SELL'));await k.stepNextEvent();const s=k.exportSnapshot('p');expect(s.accounts.a!.availableCashFen).toBe(10008890n);expect(s.accounts.a!.realizedPnlFen).toBe(8890n);expect(s.accounts.a!.lots.reduce((n,l)=>n+l.quantity,0n)).toBe(0n);});
it('B01 B02 B03 visibility and no retrospective matching',async()=>{const k=await setup();await k.advanceTo('2020-01-02T10:02:00+08:00');expect((k.query({type:'bars',securityId:'TEST_A'}) as {barEnd:string}[]).every(b=>ms(b.barEnd)<=ms('2020-01-02T10:00:00+08:00'))).toBe(true);await k.execute(order('late','BUY'));await k.advanceTo('2020-01-02T10:05:00+08:00');expect(k.exportSnapshot('p').trades).toHaveLength(0);await k.advanceTo('2020-01-02T10:10:00+08:00');expect(k.exportSnapshot('p').trades).toHaveLength(1);await k.execute(order('boundary','BUY'));expect(k.exportSnapshot('p').trades).toHaveLength(1);await k.stepNextEvent();expect(k.exportSnapshot('p').trades).toHaveLength(2);});
it('B10 missing stops before inconsistent batch and B11 ends',async()=>{const data=loadScenario('scenarios/synthetic/kernel-smoke');data.pack.bars=data.pack.bars.filter(b=>!(b.securityId==='TEST_A'&&ms(b.barEnd)===ms('2020-01-02T09:40:00+08:00')));const k=await GameKernel.create({runId:'r',ownerActorId:'p'},validatedData(data.pack),new MemoryRunStore());expect(await k.advanceTo('2020-01-02T15:00:00+08:00')).toMatchObject({ok:false,code:'DATA_PENDING',gameTime:ms('2020-01-02T09:35:00+08:00')});const complete=await setup();expect((await complete.advanceTo('2021-01-01T00:00:00Z')).code).toBe('SCENARIO_COMPLETE');});
it('B12 tick and batch yield identical logical events',async()=>{const a=await setup(),b=await setup();await a.execute(order('buy','BUY','200'));await b.execute(order('buy','BUY','200'));const end=ms('2020-01-03T15:00:00+08:00');await a.advanceTo(end);while(b.exportSnapshot('p').gameTime<end)await b.stepNextEvent();const sa=a.exportSnapshot('p'),sb=b.exportSnapshot('p');sa.stateVersion=sb.stateVersion=0;expect(sa).toEqual(sb);});
